Repository argmaxinc/WhisperKit, pull requests merged in 2024-03, with the labels that each got.

#51 Implement selecting input device
  Examples/WhisperAX/WhisperAX/Views/ContentView.swift
  Sources/WhisperKit/Core/AudioProcessor.swift
Labels: feature

#40 macOS 13 support
  .github/workflows/unit-tests.yml
  Package.swift
  Sources/WhisperKit/Core/AudioEncoder.swift
  Sources/WhisperKit/Core/AudioProcessor.swift
  Sources/WhisperKit/Core/AudioStreamTranscriber.swift
  Sources/WhisperKit/Core/FeatureExtractor.swift
  Sources/WhisperKit/Core/LogitsFilter.swift
  Sources/WhisperKit/Core/Models.swift
  Sources/WhisperKit/Core/SegmentSeeker.swift
  Sources/WhisperKit/Core/TextDecoder.swift
  Sources/WhisperKit/Core/TokenSampler.swift
  Sources/WhisperKit/Core/Utils.swift
  Sources/WhisperKit/Core/WhisperKit.swift
  Sources/WhisperKitCLI/transcribe.swift
  Tests/WhisperKitTests/FunctionalTests.swift
  Tests/WhisperKitTests/UnitTests.swift
Labels: enhancement, triaged

#52 Issue - 42 WhisperKit support simulator fixed
  Examples/WhisperAX/WhisperAX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Examples/WhisperAX/WhisperAXWatchApp/WhisperAXExampleView.swift
  Sources/WhisperKit/Core/AudioProcessor.swift
  Sources/WhisperKit/Core/Models.swift
  Sources/WhisperKit/Core/Utils.swift
Labels: enhancement

#48 skip functional tests for models that are not downloaded.
  Examples/WhisperAX/WhisperAX/Views/ContentView.swift
  Examples/WhisperAX/WhisperAXWatchApp/WhisperAXExampleView.swift
  Sources/WhisperKit/Core/Models.swift
  Tests/WhisperKitTests/UnitTests.swift
Labels: enhancement

#83 Use GPU for audio encoder on macOS 13
  Sources/WhisperKit/Core/Models.swift
  Sources/WhisperKitCLI/CLIArguments.swift
  Sources/WhisperKitCLI/Transcribe.swift
Labels: bug

#85 CLI Task Handling
  .github/workflows/development-tests.yml
  Sources/WhisperKitCLI/CLIArguments.swift
  Sources/WhisperKitCLI/Transcribe.swift
Labels: enhancement
